### ISSUE TITLE
 Not an issue but an idea

### ISSUE THREAD

**Issue by simon88** [danak6jq/Seeed-LoRa-E5#6]
Hi @danak6jq this is not an issue but maybe an idea, it would be nice to have ping-pong example from ST working with lora-e5, this example is full LoRa example without LoRaWan and I think it would be nice to have it in you repo ;)

**Comment by danak6jq** [comment]
This repo is for one specific example - the LoRaWAN_End_Node example - support for the ping-pong example would live in another repo. One is welcome to make use of the BSP from this repo in porting the ping-pong example.
