### ISSUE TITLE
Issue building project

### ISSUE THREAD

**Issue by scott1423** [danak6jq/Seeed-LoRa-E5#7]
Hi
  I have the latest ST Cube MX, IDE etc, and having issues with building the project.

I done the following:
 1. Copied the code from here into my working folder.
 2. Tried opening the project in the IDE, but nothing there.
 3. I opened the project in the cubeMX and created the project, then tried opening project, but again no project within the IDE was displayed.
 
Do I have to load a project in first, before loading (overwriting ) files from this page?

Many Thanks
Scott

**Comment by scott1423** [comment]
Hi,
  Thanks for the reply.

1. I downloaded your source code to my working folder.
2. I ran the IDE and selected the project, as follows:
![image](https://user-images.githubusercontent.com/48857509/153766668-155bf373-ec00-44b8-820f-fa52b3e39cff.png)
3. I selected the folder as follows:
![image](https://user-images.githubusercontent.com/48857509/153766712-6030e70e-96ca-47ba-822f-b5fa2cd604d5.png)
4. Then pressed finish.
5. Nothing appears , as follows:
![image](https://user-images.githubusercontent.com/48857509/153766815-fcd64b4b-491a-4ddd-a15f-f99337aa3a70.png)
6. I then opened it up in cubeMX and then Generated project. All seem to be generated going by cubeMX screen. I selected open project but got no project.

Not sure what I am doing wrong :(

Many thanks
Scott

**Comment by danak6jq** [comment]
I created C:\Work, downloaded the repo as a zip-file, extracted to C:\Work

![image](https://user-images.githubusercontent.com/942815/153767437-8de29862-6895-436c-90f3-d035b47a2b67.png)

Then opened the 'Projects from filesystem' dialog:

![image](https://user-images.githubusercontent.com/942815/153767464-89267e28-aff4-4409-9c87-f01fe0a20713.png)

Which makes me think the correct directory to import from is:

![image](https://user-images.githubusercontent.com/942815/153767582-a78408bb-4a83-447a-974c-e4da9e4b0a06.png)

Which imports this project:

![image](https://user-images.githubusercontent.com/942815/153767610-e8b39374-2593-4a1b-8a7b-53041c10b6be.png)

STM32CubeIDE is pointing out the project's name is really Seeed-LoRa-E5 even though the directory has '-master' appended.
But it did import the project, which builds just fine.

Which version of STM32CubeIDE are you using?

![image](https://user-images.githubusercontent.com/942815/153767706-3408dfe7-2bca-4f77-9bc0-5aa51a09cb24.png)

I've updated mine to v1.8.0 but I believe v1.7.0 will work.

Here, I've renamed the folder to remove -master before importing:

![image](https://user-images.githubusercontent.com/942815/153767803-adb5ac30-b480-4d71-918c-83e2eb414cb6.png)

and STM32CubeIDE doesn't mention the directory name now:

![image](https://user-images.githubusercontent.com/942815/153767840-e7687902-24e6-4070-80cc-17e73f395634.png)

and this builds as expected:

![image](https://user-images.githubusercontent.com/942815/153767872-b5acfc50-82ba-4052-8784-2cf7abc8f1cc.png)

**Comment by scott1423** [comment]
Hi
  I cleaned out my work folder, and followed what you had above, and works now.  I am also using the same version of IDE as you.  I entered my app and network key, but doesnt seam to join, see below log file. Any idea why this is? 

Many thanks
Scott

APP_VERSION:        V1.1.0
MW_LORAWAN_VERSION: V2.3.0
MW_RADIO_VERSION:   V1.1.0
###### OTAA ######
###### AppKey:      8B:0C:9A:82:E6:74:A5:11:B9:E5:26:A9:11:87:EB:84
###### NwkKey:      3A:09:42:6C:23:0B:F8:83:40:B0:40:24:1C:DD:47:C3
###### ABP  ######
###### AppSKey:     2B:7E:15:16:28:AE:D2:A6:AB:F7:15:88:09:CF:4F:3C
###### NwkSKey:     2B:7E:15:16:28:AE:D2:A6:AB:F7:15:88:09:CF:4F:3C
###### DevEui:  2C:F7:F1:20:32:30:52:2C
###### AppEui:  80:00:00:00:00:00:00:06
###### DevAddr: 00:17:FE:06
0s040:TX on freq 868500000 Hz at DR 0

[2022-02-13 18:52:06.732]# RECV ASCII>
1s527:MAC txDone

[2022-02-13 18:52:11.764]# RECV ASCII>
6s561:RX_1 on freq 868500000 Hz at DR 0

[2022-02-13 18:52:11.971]# RECV ASCII>
6s759:IRQ_RX_TX_TIMEOUT
6s759:MAC rxTimeOut

[2022-02-13 18:52:12.768]# RECV ASCII>
7s561:RX_2 on freq 869525000 Hz at DR 0

[2022-02-13 18:52:12.970]# RECV ASCII>
7s759:IRQ_RX_TX_TIMEOUT
7s759:MAC rxTimeOut

###### = JOIN FAILED

###### = RE-TRYING OTAA JOIN
7s765:TX on freq 868100000 Hz at DR 0

[2022-02-13 18:52:14.455]# RECV ASCII>
9s252:MAC txDone

[2022-02-13 18:52:15.251]# RECV ASCII>
10s044:temp= 22

10s044:VDDA= 254

[2022-02-13 18:52:19.501]# RECV ASCII>
14s287:RX_1 on freq 868100000 Hz at DR 0

[2022-02-13 18:52:19.685]# RECV ASCII>
14s485:IRQ_RX_TX_TIMEOUT
14s485:MAC rxTimeOut

**Comment by danak6jq** [comment]
What do you see on your server logs for your gateway? Do you see the join requests? I see you're EU868, right?

**Comment by scott1423** [comment]
Hi,
  Yes, I am on 868MHz.  It is a bit confusing, especially as I am new to Lora :)

Looking on the End Device screen I have it set as following:
![image](https://user-images.githubusercontent.com/48857509/153771163-c442715d-f537-480a-a458-8217657b2206.png)

![image](https://user-images.githubusercontent.com/48857509/153771207-d2201ee3-3c27-4cdd-aab3-0f6307a951cc.png)

And on the Gateway screen I have:

![image](https://user-images.githubusercontent.com/48857509/153771245-294b6cd0-94b0-4d33-844e-0f2e5c996d03.png)

**Comment by scott1423** [comment]
> Glad I could help! Enjoy.

Many thanks again for all your help. Im now getting packets of data to TTN server ..  I was wondering if you have managed to be able to set commands within the Lora E5? For eample, how would I set transmition channel, and change the spreading factor. If you have any idea, would you mind passing this on?

Many thanks again

Scott

**Comment by danak6jq** [comment]
The STM32WL in the LoRa-E5 is well-supported by ST firmware and documentation, so you'll want to look at the ST site. For example,  though the naming of this seems odd, this manual describes the APIs to the LoRaWAN layer in section 4.6 and 4.7:

https://www.st.com/resource/en/user_manual/dm00300436-stm32-lora-expansion-package-for-stm32cube-stmicroelectronics.pdf

For example, to set the transmit Data Rate (which determines spreading factor), you'd use this function:

<img width="556" alt="image" src="https://user-images.githubusercontent.com/942815/153904449-3164cc1c-0b37-4abb-b080-20fe1a9ff826.png">

Note that when ADR is enabled, the network server may change DR as it sees fit.
Also, LoRaWAN protocol automatically changes channels for Uplinks.

**Comment by danak6jq** [comment]
Have a look at Table 34 in section 4.8:

<img width="432" alt="image" src="https://user-images.githubusercontent.com/942815/153926928-c3cd394b-f50c-458c-888c-dd21efb3894d.png">

Lots of cool functions there.

Generally, though, ADR enable/disable is done at initialization time:

<img width="278" alt="image" src="https://user-images.githubusercontent.com/942815/153927968-c94d223f-256c-454e-90e8-2d9d6099a42b.png">

<img width="424" alt="image" src="https://user-images.githubusercontent.com/942815/153928067-b7732dcc-f6d0-4d63-b327-a7c941d710a2.png">

that's in lora_app.c

**Comment by scott1423** [comment]
Many thanks again... Very much appreciated, again. You have been a great help.

Best Regards
Scott

**Comment by danak6jq** [comment]
You're very welcome, @scott1423

**Comment by scott1423** [comment]
Hi
  I have been using your project a while, and all working great. I was wondering if you can give a bit of advice? I wish to have 1 device as a server, and other nodes sending lora packets to it. Any idea the best way to go here?

Many thanks again
Scott
